CREATE SEQUENCE author_sequence INCREMENT 50 START 50 MINVALUE 1;
CREATE SEQUENCE book_sequence INCREMENT 50 START 50 MINVALUE 1;
CREATE SEQUENCE reader_seq INCREMENT 50 START 50 MINVALUE 1;
CREATE SEQUENCE distribution_seq INCREMENT 50 START 60 MINVALUE 1;
CREATE SEQUENCE rental_period_seq INCREMENT 50 START 50 MINVALUE 1;